apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: platform-browsers
  annotations:
    description: |
      A task that does something cool with platforms and browsers
spec:
  params:
    - name: platform
    - name: browser
  steps:
    - name: echo
      image: alpine
      script: |
        echo "$(params.platform) and $(params.browser)"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: matrixed-pr-
spec:
  serviceAccountName: "default"
  pipelineSpec:
    tasks:
      - name: platforms-and-browsers
        matrix:
          params:
            - name: platform
              value:
                - linux
                - mac
                - windows
            - name: browser
              value:
                - chrome
                - safari
                - firefox
        taskRef:
          name: platform-browsers
      - name: matrix-and-params
        matrix:
          params:
            - name: platform
              value:
                - linux
                - mac
                - windows
        params:
          - name: browser
            value: chrome
        taskRef:
          name: platform-browsers
      - name: matrix-params-with-empty-array-skipped
        matrix:
          params:
            - name: version
              value: []
        taskSpec:
          params:
            - name: version
          steps:
            - name: echo
              image: ubuntu
              script: exit 1
    finally:
      - name: matrix-params-with-empty-array-skipped-in-finally
        matrix:
          params:
            - name: version
              value: []
        taskSpec:
          params:
            - name: version
          steps:
            - name: echo
              image: ubuntu
              script: exit 1
